language: python

python: '3.6'
sudo: false

env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1

before_install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls true
  - conda config -f --add channels conda-forge
  - conda config -f --add channels defaults
  - conda info -a

install:
  - conda env create -n aws-dev -f $TRAVIS_BUILD_DIR/conda-dev-env.yml
  - source activate aws-dev
  - conda list

script:
  # run tests
  - py.test -vv -r sxX

before_deploy:
  # create folders
  - mkdir -p dist

  # emr deployment
  - mkdir -p dist/emr
  - cp -r emr/bootstrap_actions dist/emr/bootstrap_actions

deploy:
  provider:          s3
  access_key_id:     $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket:            $AWS_BUCKET
  region:            $AWS_BUCKET_REGION
  local_dir:         dist
  upload-dir:        deployments/aws-dev
  acl:               private
  skip_cleanup:      true
  on:
    all_branches: true

notifications:
  email: true
