stack_name: 'StreamToS3-Stack'

s3_destination_bucket: 'nicor-data-stream'
s3_deployment_bucket: 'nicor-dev'

s3_key_lambda_stream_to_firehose: 'deployments/lambdas/link_kinesis_stream_to_firehose.zip'

kinesis_stream_name: 'DevStream'
kinesis_delivery_stream_name: 'DevDeliveryStream'
lambda_function_name: 'link_kinesis_stream_to_firehose'
