AWSTemplateFormatVersion: '2010-09-09'
Description: Dev Server Stack
Outputs:
  DevServer:
    Description: EC2 Instance
    Value: !Ref 'DevServer'
Resources:
  DevServer:
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            download_miniconda:
              command: su - ec2-user -c "wget http://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh
                -O /home/ec2-user/miniconda.sh"
            install_miniconda:
              command: su - ec2-user -c "bash /home/ec2-user/miniconda.sh -b -p /home/ec2-user/miniconda"
            remove_installer:
              command: rm -rf /home/ec2-user/miniconda.sh
            update_yum_packages:
              command: yum update -y
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Join ['', ['[main]

                    ', stack=, !Ref 'AWS::StackId', '

                    ', region=, !Ref 'AWS::Region', '

                    ', interval=2, '

                    ']]
              group: root
              mode: '000400'
              owner: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Join ['', ['[cfn-auto-reloader-hook]

                    ', 'triggers=post.update

                    ', 'path=Resources.DevServer.Metadata.AWS::CloudFormation::Init

                    ', action=/opt/aws/bin/cfn-init -v, ' --stack ', !Ref 'AWS::StackId',
                  ' --resource DevServer', ' --region ', !Ref 'AWS::Region', '

                    runas=root

                    ']]
            /home/ec2-user/.bashrc:
              content: !Join ['', ['export PATH="/home/ec2-user/miniconda/bin:$PATH"

                    ']]
              group: ec2-user
              mode: '000400'
              owner: ec2-user
          services:
            sysvinit:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                - /etc/cfn/cfn-hup.conf
                - /etc/cfn/hooks.d/cfn-auto-reloader.conf
    Properties:
      ImageId: ami-d7b9a2b1
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t2.micro
      KeyName: nicor88-dev
      Monitoring: 'true'
      SecurityGroupIds:
      - sg-389f2740
      SubnetId: subnet-43ab5018
      Tags:
      - Key: Name
        Value: dev-server
      - Key: StackName
        Value: !Ref 'AWS::StackName'
      UserData: !Base64
        Fn::Join:
        - ''
        - - '#!/bin/bash -xe

            '
          - '/opt/aws/bin/cfn-init -v '
          - ' --stack '
          - !Ref 'AWS::StackName'
          - ' --resource DevServer'
          - ' --region '
          - !Ref 'AWS::Region'
          - '

            '
          - 'yum install -y aws-cfn-bootstrap

            '
          - /opt/aws/bin/cfn-hup || error_exit "Failed to start cfn-hup"
          - '

            '
          - '/opt/aws/bin/cfn-signal -e $? '
          - ' --stack '
          - !Ref 'AWS::StackName'
          - ' --resource DevServer'
          - ' --region '
          - !Ref 'AWS::Region'
          - '

            '
    Type: AWS::EC2::Instance
