AWSTemplateFormatVersion: '2010-09-09'
Description: Collection of Lambda Function
Outputs:
  HelloWorldLambda:
    Description: HelloWorld Lambda Function
    Value: !Ref 'HelloWorldFunction'
  HelloWorldLambdaArn:
    Description: HelloWorld Arn of Lambda Function
    Value: !GetAtt [HelloWorldFunction, Arn]
  LambdaExecutionRole:
    Description: Lambdas Execution role
    Value: !Ref 'ExecutionRole'
Parameters:
  KMSArn:
    Description: KMS arn used inside the lambda
    Type: String
Resources:
  ExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
            - arn:aws:logs:*:*:*
            Sid: Logs
          Version: '2012-10-17'
        PolicyName: GrantLogs
      - PolicyDocument:
          Statement:
          - Action:
            - kms:*
            Effect: Allow
            Resource:
            - '*'
            Sid: Kms
          Version: '2012-10-17'
        PolicyName: KMS
      RoleName: ExecutionRole-ExampleLambdasStack
    Type: AWS::IAM::Role
  HelloWorldEncVarsFunction:
    Properties:
      Code:
        S3Bucket: nicor-dev
        S3Key: deployments/lambdas/travis_build/hello_world.zip
      Description: Hello world lambdas with encrypted vars Python 3.6
      Environment:
        Variables:
          SAMPLE_VAR: AQICAHhF8ODh0YKuqTU0H95UxE9cqgvlUixFYzJFVTSkZ9pIwAESnleVwQKwP585ulyc/ibCAAAAYjBgBgkqhkiG9w0BBwagUzBRAgEAMEwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrIH0nJzULmZpIBqbAgEQgB8PvwaiR0H4wjAl3NKtG+rrwnXOlQSIfD4TCY6wci+4
      FunctionName: hello_world_enc_vars
      Handler: lambda_function.lambda_handler
      KmsKeyArn: !Ref 'KMSArn'
      MemorySize: 128
      Role: !GetAtt [ExecutionRole, Arn]
      Runtime: python3.6
      Timeout: '30'
    Type: AWS::Lambda::Function
  HelloWorldFunction:
    Properties:
      Code:
        S3Bucket: nicor-dev
        S3Key: deployments/lambdas/travis_build/hello_world.zip
      Description: Hello world lambdas with Python 3.6
      FunctionName: hello_world
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt [ExecutionRole, Arn]
      Runtime: python3.6
      Timeout: '30'
    Type: AWS::Lambda::Function
